// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljcqrmifcyakkuphqinp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqY3FybWlmY3lha2t1cGhxaW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzU2NzEsImV4cCI6MjA3MzM1MTY3MX0.6BN_CRlE1xQeIz9G4a1Kq4Hn977p1fbofk2GZHK0Izo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});